const content = document.getElementById('appContent');
const title = document.getElementById('appTitle');
const greeting = document.getElementById('appGreeting');
const modal = document.getElementById('modal');
const modalTitle = document.getElementById('modalTitle');
const modalText = document.getElementById('modalText');

const overview = () => `<div class="dash-stats"><div class="dash-stat"><small>UPCOMING EVENTS</small><b>06</b><em>+2 this week</em></div><div class="dash-stat"><small>TASKS COMPLETED</small><b>08 <span>/ 12</span></b><em>66% complete</em></div><div class="dash-stat"><small>FOCUS TIME</small><b>4h 20m</b><em>↗ 18% vs last week</em></div><div class="dash-stat"><small>DAILY STREAK</small><b>🔥 14</b><em>Personal best!</em></div></div><div class="dash-body"><div><div class="dash-heading"><h4>Today’s schedule</h4><button data-open="Calendar">View calendar →</button></div><div class="schedule-item"><time>09:30<br>AM</time><div><b>Advanced UI Workshop</b><small>Innovation Lab · Room 402</small></div></div><div class="schedule-item purple-s"><time>12:45<br>PM</time><div><b>Team Project Sync</b><small>Online · Google Meet</small></div></div><div class="schedule-item red-s"><time>03:00<br>PM</time><div><b>Algorithms Assignment</b><small>Deadline today</small></div></div><div class="quick-actions"><h4>Quick actions</h4><div class="quick-buttons"><button data-open="New event">＋ Add event</button><button data-open="Reminder set">☆ Set reminder</button><button data-open="Faculty message">◌ Message faculty</button></div></div></div><aside class="progress-card"><h4>Your weekly progress</h4><div class="progress-ring"><b>78%</b><small>COMPLETE</small></div><div class="quick-actions"><h4>Up next</h4><small style="color:#c4b5fd;font-size:9px">✦ Machine Learning</small><small style="display:block;color:#8290a9;font-size:8px;margin-top:5px">Tomorrow · 10:00 AM</small></div></aside></div>`;
const calendar = () => {const days=['MON','TUE','WED','THU','FRI','SAT','SUN'];let cells='';for(let i=1;i<=35;i++){const d=i-2;const event=d===8?'<span class="event-pill">UI Workshop</span>':d===10?'<span class="event-pill deadline">Assignment</span>':d===17?'<span class="event-pill hack">Hackathon</span>':d===23?'<span class="event-pill done">Completed</span>':'';cells+=`<td class="${d===8?'today-cell':''}">${d>0&&d<32?d:''}${event}</td>`}return `<div class="calendar-view"><div class="dash-heading"><h4>October 2024</h4><button data-open="New calendar event">＋ Create event</button></div><table class="full-calendar"><thead><tr>${days.map(d=>`<th>${d}</th>`).join('')}</tr></thead><tbody>${Array.from({length:5},(_,i)=>`<tr>${cells.slice(i*0,0)}${Array.from({length:7},(_,j)=>{let n=i*7+j-1;let event=n===8?'<span class="event-pill">UI Workshop</span>':n===10?'<span class="event-pill deadline">Assignment</span>':n===17?'<span class="event-pill hack">HackFusion</span>':n===23?'<span class="event-pill done">Completed</span>':'';return `<td class="${n===8?'today-cell':''}">${n>0&&n<32?n:''}${event}</td>`}).join('')}</tr>`).join('')}</tbody></table><p style="font-size:9px;color:#8190a9">Blue = Personal · Red = Deadline · Purple = Hackathon · Green = Completed</p></div>`};
const lists={schedule:['Advanced UI Workshop|Today, 09:30 AM|Innovation Lab','Team Project Sync|Today, 12:45 PM|Google Meet','Machine Learning|Tomorrow, 10:00 AM|Block C, 201'],assignments:['Algorithms Assignment|Due today, 3:00 PM|High priority','Database Lab Report|Due Oct 11|In progress','UX Research Notes|Due Oct 14|Not started'],hackathons:['HackFusion ’24|Online · October 20–22|$25,000 in prizes','CodeForward|Hybrid · October 16–18|$15,000 in prizes','GreenSpark|On campus · October 29–31|$10,000 in prizes']};
function makeList(kind){if(kind==='notifications')return `<div class="announcement-list"><h4>Faculty announcements</h4><div class="chat"><div class="chat-head"><span>DP</span><div><b>Prof. David Park</b><small> · 2 min ago</small></div><em>NEW</em></div><p>Great work on the midterms, everyone! Feedback is now available in the portal.</p></div><div class="chat"><div class="chat-head"><span>LM</span><div><b>Dr. Lisa Morgan</b><small> · Yesterday</small></div></div><p>Tomorrow’s lecture will be held online. Meeting link has been updated.</p></div></div>`;if(kind==='reminders')return `<div class="list-view"><div class="dash-heading"><h4>Smart reminders</h4><button data-open="New reminder">＋ Add reminder</button></div><div class="reminder-card"><span>☆</span><div><b>Submit Algorithms Assignment</b><small>Today · 2:30 PM</small></div><button>★</button></div><div class="reminder-card"><span>♧</span><div><b>Project team meeting</b><small>Today · 12:30 PM</small></div><button>☆</button></div><div class="reminder-card"><span>☆</span><div><b>Register for HackFusion</b><small>October 18 · 10:00 AM</small></div><button>★</button></div></div>`;if(kind==='profile')return `<div class="list-view"><h4>Profile & achievements</h4><div class="assignment"><i>RK</i><div><b>Ryan Kapoor</b><small>Computer Science · Class of 2026</small></div></div><div class="dash-stats"><div class="dash-stat"><small>PRODUCTIVITY</small><b>87%</b></div><div class="dash-stat"><small>LONGEST STREAK</small><b>🔥 21</b></div></div></div>`;return `<div class="list-view"><div class="dash-heading"><h4>${kind==='hackathons'?'Open opportunities':kind==='assignments'?'Your assignments':'My schedule'}</h4><button data-open="New item">＋ Add new</button></div>${lists[kind].map((x,i)=>{let [a,b,c]=x.split('|');return `<div class="assignment"><i>${kind==='hackathons'?'♕':kind==='assignments'?'✓':'◷'}</i><div><b>${a}</b><small>${b} · ${c}</small></div><em>${kind==='assignments'?'DUE SOON':'View →'}</em></div>`}).join('')}</div>`}
const labels={overview:['TUESDAY, OCTOBER 8','Good morning, Ryan ✦'],calendar:['OCTOBER 2024','Your smart calendar'],schedule:['TODAY','My schedule'],assignments:['STAY AHEAD','Assignments'],hackathons:['OPPORTUNITIES','Hackathons'],notifications:['YOUR INBOX','Notifications'],reminders:['SMART SUPPORT','Reminders'],profile:['YOUR SPACE','Profile']};
function showView(view){document.querySelectorAll('.app-nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));[greeting.textContent,title.textContent]=labels[view];content.innerHTML=view==='overview'?overview():view==='calendar'?calendar():makeList(view);}
showView('overview');
document.querySelector('.app-sidebar').addEventListener('click',e=>{const btn=e.target.closest('.app-nav');if(btn)showView(btn.dataset.view)});
document.querySelectorAll('.role-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.role-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const faculty=btn.dataset.role==='faculty';document.getElementById('roleTitle').textContent=faculty?'Keep your whole class connected.':'Your entire academic world, in one place.';document.getElementById('roleDesc').textContent=faculty?'Create events, reach students instantly, and see engagement at a glance.':'Organize your schedule, stay ahead of deadlines, and make every day count.';document.querySelectorAll('.app-nav em').forEach((x,i)=>{if(faculty&&i===2)x.textContent='Create Event';if(faculty&&i===3)x.textContent='Meetings'});showView('overview')}));
function openModal(t='Welcome to ELITE',p='Your smarter academic journey starts here.'){modalTitle.textContent=t;modalText.textContent=p;modal.classList.add('show')}
['navStart','heroStart','ctaStart','loginBtn'].forEach(id=>document.getElementById(id).addEventListener('click',()=>openModal(id==='loginBtn'?'Welcome back':'Your ELITE account is ready','This interactive demo is ready for your next academic win.')));
document.getElementById('previewBtn').addEventListener('click',()=>document.getElementById('experience').scrollIntoView({behavior:'smooth'}));
document.getElementById('exploreBtn').addEventListener('click',()=>document.getElementById('dashboard').scrollIntoView({behavior:'smooth'}));
document.getElementById('viewAllHackathons').addEventListener('click',()=>showView('hackathons'));
document.addEventListener('click',e=>{if(e.target.closest('.modal-close')||e.target===modal)modal.classList.remove('show');const b=e.target.closest('[data-open]');if(b)openModal(b.dataset.open,'We’ve prepared this action for you in the ELITE workspace.');if(e.target.closest('.register-btn,.circle-arrow'))openModal('Registration started','You’re one step closer to your next big build.')});
